### ISSUE TITLE
Assign sites screen lacks information for clear identification

### ISSUE THREAD

**Issue by Japh** [johnjamesjacoby/wp-multi-network#25]
On a multi network installation when using the "Assign Sites" screen to move sites from one network to another, there isn't enough information displayed to uniquely identify similarly named sites.

It might be useful to show include the site ID, or sub-domain.

**Comment by Japh** [comment]
cc/ @rmccue

**Comment by johnjamesjacoby** [comment]
Related to #25

**Comment by johnjamesjacoby** [comment]
This is improved in master for what will be the 1.7.0 release.
