### ISSUE TITLE
UI for the assign sites screen is cumbersome for large volumes

### ISSUE THREAD

**Issue by Japh** [johnjamesjacoby/wp-multi-network#26]
If there are large numbers of sites on either side of the equation when assigning sites to different networks, it's very difficult to find and identify specific sites.

Possibly adding the ability to search / filter the multiple select fields would help mitigate the difficult dealing with large volumes.

**Comment by Japh** [comment]
cc/ @rmccue

**Comment by kaichi** [comment]
Are you trying to move subdomains to other Networks in this scenario? I wanted to provide feedback from what I see from my perspective. I have mainly networks/domains.

I agree, my only work around that is not intuitive: typing the domain out when the drop down menu is highlighted. The downside is that you have to know exactly how the domain is spelled to get through a ton of domains (say if you have domain names with similar names). Another con is if you have to many subdomains/domains with "keywords" you might struggle to find the exact same domain. Say, 20 or 30 domains have similar words.

**Comment by johnjamesjacoby** [comment]
I agree, that this UI needs improvement.

It also just generally looks dated compared to recent attention to `wp-admin` in general.

I'll look at improving this soon.

**Comment by johnjamesjacoby** [comment]
This was improved somewhat in what will be 1.7.0. There's more to do, though.

Closing for now. Let's reopen or create a new issue once we have some design direction?
