### ISSUE TITLE
Plugin lives in src

### ISSUE THREAD

**Issue by jtsternberg** [johnjamesjacoby/wp-multi-network#28]
Any reason plugin cannot be top-level instead of living in /src? It makes it much more difficult to use the git version as a WordPress plugin.

**Comment by rmccue** [comment]
@johnjamesjacoby Let's move `src/wpmn-loader.php` up to `plugin.php`? :)

**Comment by mgburns** [comment]
:+1:

**Comment by inderpreet99** [comment]
+1 from me as well. This is something we've had to do in [our fork](https://github.com/bu-ist/wp-multi-network) (bc5c3d149cdc0ad548e91519df8e26d7e5661bd3).

**Comment by spacedmonkey** [comment]
Generally make this repo a place where people can get the code. At the moment the wordpress plugin repo is version of the plugin is massively out of date. To get all the latest bug fixes and features (like my wp cli commands) you have to load from github. But with it not in the root, it makes it hard, as you can't just check the plugin out in your plugin directory. Also it would be nice to have tagged versions of the repo that are the same as the plugin version numbers.

**Comment by johnjamesjacoby** [comment]
I'm fine with getting rid of the src directory.

It was originally setup this way to be all trendy and cool and include a bunch of tests & stuff.
