### ISSUE TITLE
404 for child blogs in subnetwork

### ISSUE THREAD

**Issue by mathiasfriman** [johnjamesjacoby/wp-multi-network#32]
Multi-site with subdirectories, not subdomains as blog. Creating networks works fine. However, when assigning blogs to sub-networks, the blogs are not found.

Setup:

domain.com/network1/blog1 - 404 oops
domain.com/network1/blog2 - 404 oops
domain.com/network2/blog1 - 404 oops
domain.com/network2/blog2 - 404 oops
etc.

## Half a workaround
Changing "path" in **wp_blogs**, and "site_url", "home" in **wp_*_options** by removing the **/** displays the "frontpage" of the blog

domain.com/network1blog1 - Displays frontpage, but does not work when clicking on posts/pages
domain.com/network1blog2 - same as above
domain.com/network2blog1 - same as above
domain.com/network2blog2 - same as above

Standard Multi-site .htaccess: http://paste.debian.net/plain/152338

**Comment by johnjamesjacoby** [comment]
Are you saying there is a trailing slash in the path that does not belong?
