### ISSUE TITLE
Infinite Redirect loop

### ISSUE THREAD

**Issue by LevyImage** [johnjamesjacoby/wp-multi-network#34]
Hi,
I've update my copy of the WP repo version with your newest additions here on github,
when creating a 2nd network and going to it's url, it goes into an infinite redirect loop...
Any suggestions? thank you

**Comment by johnjamesjacoby** [comment]
Check a few things:

* Cookies & that you are logged in
* Where are you being redirected from & too?
* Is domain mapping a factor?
* Is apache/nginx/other configured to support both/all domains?
* Is any other plugin hi-jacking anything related to home & site URLs?
