### ISSUE TITLE
_network_options() functions now in WordPress 4.4

### ISSUE THREAD

**Issue by johnjamesjacoby** [johnjamesjacoby/wp-multi-network#55]
WP Multi Network causes fatal errors from duplicate function names, introduces in WordPress 4.4.

We should wrap them in `function_exists()` checks for now, and ensure core function parameters match ours.

**Comment by johnjamesjacoby** [comment]
See: https://core.trac.wordpress.org/changeset/34777

Parameter order is also in flux, ideally will change to match what we have here.

**Comment by spacedmonkey** [comment]
For what it is worth, I would have either back ported the functions from 4.4 or at the very lease changed the order of the Params to match the core. This should be a breaking change for this plugin. This will force uses to change they code to support the new functions in core. 

Just my two cents 😄
