### ISSUE TITLE
Lack of good Documentation and Example Getting Started

### ISSUE THREAD

**Issue by mdramos** [johnjamesjacoby/wp-multi-network#56]
As a user I would like some type of clear example/demo for using this plugin. So far I am failing to get the proper functionality out of it. I try to create a new network and it just doesn't work (404s, page breaking).

Users in the support page have also posted similar issues but there was never a response.
https://wordpress.org/support/topic/wp-multi-network-multisite
https://wordpress.org/support/topic/plugin-wp-multi-network-404-for-child-pages

**Comment by mdramos** [comment]
Here is a seemingly good tutorial: https://premium.wpmudev.org/blog/network-of-multisite-networks/

However troubles still arrive. I can not successfully create a separate network and add sites to it. All of my testing is done from fresh installs.

**Comment by johnjamesjacoby** [comment]
Thanks for the feedback, but there's not much actionable here. The plugin itself works very well, and I agree that much of it's functionality is relatively invisible. We can look at video tutorials or something to pitch it more, but that doesn't help you with your "everything is broken" problem.

I'm going to close this issue, and ask that if you have any specific ones, you please create new issues for each of them so they can be addressed individually.
