### ISSUE TITLE
Move repository underneath Stuttter organization

### ISSUE THREAD

**Issue by johnjamesjacoby** [johnjamesjacoby/wp-multi-network#58]
I'd like to move this plugin into the Stuttter organization, but want to make sure there are no objections from other contributors, @rmccue specifically who's been active recently.

https://github.com/stuttter/

**Comment by spacedmonkey** [comment]
All good with me :+1:

**Comment by johnjamesjacoby** [comment]
Great. Thanks @spacedmonkey!

**Comment by rmccue** [comment]
I have no opinion either way, so feel free to move it :)

**Comment by johnjamesjacoby** [comment]
Thanks @rmccue!
